# action.yml
name: "Blockless Function Publish"
description: "Publish a Function to IPFS"
branding:
  icon: "box"
  color: "green"
runs:
  using: "composite"
  steps:
    - name: Build and Publish
      shell: bash
      run: |-
        bls function deploy
